### PR TITLE
Allow non-secure contexts (configurable)

### PR DESCRIPTION
**Pull request by kullmanp**
Sometimes it is necessary to allow authentication (even basic auth) over
an open insecure line: 
- Test environments (in the IDE)
- Behind reverse Proxies where SSL handling is done by the proxy

This change allows to use the authenticator filter even if the servlet
request says it's not secure.

BTW: A missing return statement is added.

### CODE REVIEW

**Comment by pkriens** [comment]
Are you going to update this PR?

**Comment by bjhargrave** [comment]
> Are you going to update this PR?

I think it has been updated, `allowAuthOverNonSecureLine`,  but the commit message is missing the necessary `Signed-off-by` statement.

**Comment by kullmanp** [comment]
I don't have time to work on this at the moment. Please use it if you want.

**Comment by pkriens** [comment]
We can't unless it is signed off :-( Would appreciate it you could spend the 5 mins to sign your contribution off. Thanks.

**Comment by kullmanp** [comment]
I changed (amended) my local commit so as to include a signed-off line and pushed (with --force) it to my forge. But it doesn't show up there.

**Comment by bjhargrave** [comment]
I see it above. But you need to rebase and resolve conflicts. It cannot be merged as it stands now.

**Pull request closed without merging**
