### PR TITLE
Configurations purge functionality

### PR DESCRIPTION
**Pull request by dpishchukhin**
- purge configurations on configuration bundle stop
- purge configuration on configurator bundle stop
- replace string concatenation in logs with String.format()

Signed-off-by: Dmytro Pishchukhin dmytro.pishchukhin@gmail.com

### CODE REVIEW

**Comment by pkriens** [comment]
I don't think it is a good idea to remove the configurations when the bundle is stopped. One could make the case for an uninstall but stop is too transient.

**Comment by dpishchukhin** [comment]
Agree. This means we can add configurations from a bundle that is resolved, not activated.

**Comment by pkriens** [comment]
That actually might work out well because it means configuration is set before the bundles are started. This might improve the bouncing.

**Comment by dpishchukhin** [comment]
Correct me if I'm wrong. 

Configurer tracks all bundles with state min RESOLVED and tries to find configuration.json file inside. If a bundle with configuration changes state to INSTALLED or UNINSTALLED, configurer purge configurations.

**Comment by pkriens** [comment]
I think on UNINSTALLED only, INSTALLED might be transient. However, this creates the responsibility to look at your startup if their any configurations of bundles that are not installed since you might have missed the event.

**Comment by dpishchukhin** [comment]
I see. It's a good point for a new issue.

The pull request suits well for show cases when configuration could be activated and deactivated in runtime. In current version, we can only create configuration with configuration bundle.

**Comment by pkriens** [comment]
@dpishchukhin : Where are we on this?

**Comment by dpishchukhin** [comment]
Peter,

there were some changes in the module since my last update. I'll provide a new commit that includes all last changes.

**Comment by dpishchukhin** [comment]
will provide a new PL.

**Pull request closed without merging**
