### PR TITLE
Additional tests for Dispatch Servlet

### PR DESCRIPTION
**Pull request by dleangen**
Continuation of https://github.com/osgi/osgi.enroute.bundles/pull/23.

### CODE REVIEW

**Comment by dleangen** [comment]
I added a few more TestServlets to the ranking test, just to be sure. :-)

Sorry to be such a dunce, but I was not able to configure the DispatchServlet. I want to make the delisting ~ 3 seconds instead of the current default 5 minutes.

**Comment by pkriens** [comment]
You fix the Appveyor problem? If this works, I add the bundle to the enRoute release (the API is already there). Want to write an App note for this + an example? :-)

**Comment by dleangen** [comment]
Yes, happy to write an appnote, and provide an example.

The test that is failing is the stub that I added for the blacklist test. I have not yet been able to configure the DispatchServlet in this text context, for some reason. If you have a tip to get the config working, that would speed things up. :-) Sorry for stumbling on what should be basic OSGi stuff. :-(

**Comment by dleangen** [comment]
Peter, 

I could not get the configuration to work in the test environment, so I did not add any new tests after all. If ever you have an idea how to make configuration work for tests, would be delighted to know!

The Appveyor problem is now fixed. The test bundle was just missing the junit depenedency.

If you release this, I will work on an AppNote + example, after I have integrated it into my stuff and removed my local patched version. :-)

**Comment by pkriens** [comment]
I've added the configuration and found out how good it is to do testing! There were two bugs in the blacklisting :-)

Please verify.

**Comment by dleangen** [comment]
Ohhhhh, so thaaaaat's how the configuration works. Got it!!!

Yes, I'll work on this very soon. Thanks so much!!

**Comment by dleangen** [comment]
Hi Peter,

I have verified the changes and the tests. Looks good.

Thanks so much for this. I am learning a lot working with you guys. Thanks for your patience. I'm sure I will become more and more useful. ;-)

Not sure if this PR is useful or not anymore. The remaining changes are quite trivial. Let me know if you don't merge it, and I will just close it.

**Pull request closed without merging**
