### PR TITLE
Added exception handling where obvious and added comments.

### PR DESCRIPTION
**Pull request by bcraun**
Simple refactorings to enhance exception handling as well as added comments. Fixed logic defect for last LogEntry loss when roll over occurs.

[roller] Squashed commits for PR. Commenting and minor refactoring. Added error handling where most obvious.

Signed-off-by: Bill Craun <bill@craun.net>

### CODE REVIEW

**Comment by pkriens** [comment]
You made a mistake at https://github.com/osgi/osgi.enroute.bundles/pull/25/files#diff-54be635852b307c40018aa99cc4ef148R113

The File.mkdirs returns false if the directory already exists. So if the directory exists you will get an exception. The previous code is by far the best solution I learned over a long period ...

**Comment by pkriens** [comment]
https://github.com/osgi/osgi.enroute.bundles/pull/25/files#diff-54be635852b307c40018aa99cc4ef148R93

I think you should make this a separate component if you need this functionality. Most software evil starts when you combine two unrelated things ... however convenient it may be.

**Comment by pkriens** [comment]
You probably want to remove sysouts and stack traces

**Comment by pkriens** [comment]
If you fix these things then I will merge it. Thanks!

**Comment by bcraun** [comment]
Peter, while testing the rollover, I'm seeing behavior that is not expected. Even when I comment out the purge() method, all log files are removed between code/debug cycles. Is this expected behavior? I would have expected that all existing log files up to the maximum retained count would be preserved between runs.

**Comment by pkriens** [comment]
That is probably why you did not detect the mkdirs() bug :-) Currently the framework is setup to clean the storage when you run start it. This is the default because it works better in debug mode.

So you can either store the logs somewhere safer (e.g. in /var on linux) or you can setup the bnd.bnd file to not clean the storage. You can set `-runkeep=true` in the bnd.bnd file.

**Comment by bcraun** [comment]
Yup. :) I tested using /var/tmp/xxx and it works as expected. Updated a couple of variable names for clarity.

**Comment by bcraun** [comment]
Updates completed. Commits squashed and signed off. Ready for merge.

**Comment by pkriens** [comment]
abort :-( At https://github.com/osgi/osgi.enroute.bundles/pull/25/files#diff-54be635852b307c40018aa99cc4ef148R160 you reorder the log by queueing the entry again if the file is too large. I had not seen that before but I think this is wrong. Since we do not have sequence numbers this might be confusing (and potential attack vector.) So I would ALWAYS write and then check.

**Comment by bcraun** [comment]
Size check logic reverted to always write then check.

**Comment by pkriens** [comment]
And we have a take off ...

**Comment by pkriens** [comment]
Thanks!

**Pull request merged**
