### PR TITLE
DispatchServlet (cleaned)

### PR DESCRIPTION
**Pull request by dleangen**
Hi Peter,

I thought it would be simpler to just create a new, clean PR based on [this one](https://github.com/osgi/osgi.enroute.bundles/pull/18).

I still need to apply a few of the changes you suggested, and the test cases are not working.

Regarding the test cases, I based it on what I saw in this workspace, but the wiring is not working. I'm not sure what's wrong, so would you mind taking a look?

Once you "move over" to this PR and I apply the remaining changes, I will close down the old PR.

Cheers,
=David

### CODE REVIEW

**Comment by dleangen** [comment]
I have committed the implementations of the modifications suggested by Peter and closed the old PR.

As far as I know, the only outstanding issue here is the failing tests.

**Comment by pkriens** [comment]
Done! I'll try to take a look today for the testing. Thanks!

**Comment by dleangen** [comment]
Super! Thank you very much! :-)

**Comment by dleangen** [comment]
Just thought I would ping. :-)

**Comment by pkriens** [comment]
And that does help :-)

Take a look. I've fixed the test cases, there are 4 now and they all pass. Would be nice to have a test case for the BadServlet becoming active again if you've got time.

Overall change was that the Conditional Servlet is not required to extend Servlet and it should also NOT be registered as Servlet service. 

The WebServer servlet was thus changed and now properly returns false/true if has found a resource or not.

If you take a look and maybe add a few more tests then we can push the new web provider to the distro

**Comment by dleangen** [comment]
Thank you!

I will try to take a look tomorrow. It is already late here. :-)

Should any changes go in this same branch? Or do I pull and then submit a new PR?

**Comment by bjhargrave** [comment]
> Should any changes go in this same branch? Or do I pull and then submit a new PR?

This PR is merged. So any further work should be on a new branch off the tip of master.

**Comment by dleangen** [comment]
Continued [here](https://github.com/osgi/osgi.enroute.bundles/pull/24).

**Pull request merged**
