### PR TITLE
Added Polymer web resources and demo app

### PR DESCRIPTION
**Pull request by njbartlett**
Signed-off-by: Neil Bartlett neil.bartlett@paremus.com

### CODE REVIEW

**Comment by pkriens** [comment]
Could we separate the demo app from the webresource? I'd like the app be a separate repo (osgi.enroute.examples.polymer with osgi.enroute.examples.polymer.application project) and the webresource is fine to be a bundle in this repo. (Though we need to see if we can somehow reuse the webjars.org efforts) WDYT?

**Comment by njbartlett** [comment]
Yes that's fine. Does the example app repo exist already?

**Comment by pkriens** [comment]
https://github.com/osgi/osgi.enroute.examples.polymer

* I've made you an admin on the repo
* I've added the snapshot repo for the enRoute bundles

**Comment by pkriens** [comment]
Anything happening?

**Pull request merged**
