### PR TITLE
WebResource bundle for webcomponentsjs

### PR DESCRIPTION
**Pull request by njbartlett**
Signed-off-by: Neil Bartlett <neil.bartlett@paremus.com>

### CODE REVIEW

**Comment by pkriens** [comment]
I will take a look once I've got some breathing space ...

**Comment by pkriens** [comment]
Can I yell about this? Did you tweet about it?

**Comment by njbartlett** [comment]
I haven’t tweeted anything yet.

I’m doing several more related to web components and Polymer, so maybe wait a bit? I wanted to do this small one first to make sure I’m going the right direction.

**Comment by pkriens** [comment]
Would it be possible to also create an example repo for this? 

Kind regards,

	Peter Kriens

**Pull request merged**
